"""criando a tabela filmes

Revision ID: 93124e4411a7
Revises: af80d13ab7e2
Create Date: 2025-09-11 22:18:19.333404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93124e4411a7'
down_revision = 'af80d13ab7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo_original', sa.String(length=250), nullable=False),
    sa.Column('titulo_nacional', sa.String(length=250), nullable=False),
    sa.Column('ano_lancamento', sa.Integer(), nullable=False),
    sa.Column('lancado', sa.Boolean(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('orcamento', sa.DECIMAL(), nullable=True),
    sa.Column('faturamento_lancamento', sa.DECIMAL(precision=2), nullable=True),
    sa.Column('poster_principal', sa.String(length=250), nullable=True),
    sa.Column('link_trailer', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmes')
    # ### end Alembic commands ###
